version: '3'
services:
  gpt-researcher:
    network_mode: host 
    image: assafelovic/gpt-researcher
    build: ./
    environment: 
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - 8000:8000